---
- name: Get Keycloak auth token
  ansible.builtin.uri:
    url: "{{ rabbitmq_keycloak_url }}/protocol/openid-connect/token"
    validate_certs: false
    method: POST
    body_format: form-urlencoded
    body:
      client_id: "{{ rabbitmq_keycloak_client_id }}"
      client_secret: "{{ rabbitmq_keycloak_client_secret }}"
      grant_type: client_credentials
    headers:
      Content-Type: application/x-www-form-urlencoded
    status_code:
      - 200
      - 204
  register: keycloak_token
  run_once: true
  when:
    - rabbitmq_keycloak_url is defined
    - rabbitmq_keycloak_client_id is defined
    - rabbitmq_keycloak_client_secret is defined

- name: Set RabbitMQ login credentials (OAuth2)
  ansible.builtin.set_fact:
    _rabbitmq_login_user: ""
    _rabbitmq_login_password: "{{ keycloak_token.json.access_token }}"
  when: keycloak_token is defined and not (keycloak_token.skipped | default(false))

- name: Set RabbitMQ login credentials (internal auth)
  ansible.builtin.set_fact:
    _rabbitmq_login_user: "{{ rabbitmq_admin_user }}"
    _rabbitmq_login_password: "{{ rabbitmq_admin_password }}"
  when: keycloak_token is not defined or (keycloak_token.skipped | default(false))

- name: Create RabbitMQ queues
  community.rabbitmq.rabbitmq_queue:
    name: "{{ item.name }}"
    arguments: "{{ item.arguments | default({}) | ansible.builtin.combine(rabbitmq_queue_defaults) }}"
    durable: "{{ item.durable | default(omit) }}"
    max_length: "{{ item.max_length | default(omit) }}"
    max_priority: "{{ item.max_priority | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    vhost: "{{ item.vhost | default('/') }}"
    login_protocol: "{{ 'https' if rabbitmq_ssl is defined else 'http' }}"
    login_host: "{{ item.leader | default(inventory_hostname) }}"
    login_port: "{{ (rabbitmq_management_ssl_port if rabbitmq_ssl is defined else rabbitmq_management_port) | int }}"
    login_user: "{{ _rabbitmq_login_user }}"
    login_password: "{{ _rabbitmq_login_password }}"
    ca_cert: "{{ rabbitmq_ssl.ca | default(omit) }}"
    client_cert: "{{ rabbitmq_ssl.cert | default(omit) }}"
    client_key: "{{ rabbitmq_ssl.key | default(omit) }}"
  loop: "{{ rabbitmq_queues }}"
  run_once: true

- name: Create dead letter queues
  community.rabbitmq.rabbitmq_queue:
    name: "{{ item.name }}-dlq"
    arguments: "{{ item.arguments | default({}) | ansible.builtin.combine(rabbitmq_queue_defaults) }}"
    durable: "{{ item.durable | default(omit) }}"
    max_length: "{{ item.max_length | default(omit) }}"
    max_priority: "{{ item.max_priority | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    vhost: "{{ item.vhost | default('/') }}"
    login_protocol: "{{ 'https' if rabbitmq_ssl is defined else 'http' }}"
    login_host: "{{ item.leader | default(inventory_hostname) }}"
    login_port: "{{ (rabbitmq_management_ssl_port if rabbitmq_ssl is defined else rabbitmq_management_port) | int }}"
    login_user: "{{ _rabbitmq_login_user }}"
    login_password: "{{ _rabbitmq_login_password }}"
    ca_cert: "{{ rabbitmq_ssl.ca | default(omit) }}"
    client_cert: "{{ rabbitmq_ssl.cert | default(omit) }}"
    client_key: "{{ rabbitmq_ssl.key | default(omit) }}"
  loop: "{{ rabbitmq_queues }}"
  run_once: true
  when: item.create_dlq | default(false)
