---
- name: Manage RabbitMQ users
  community.rabbitmq.rabbitmq_user:
    node: "rabbit@{{ ansible_fqdn }}"
    user: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    vhost: "{{ item.vhost | default('/') }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    tags: "{{ item.tags | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ rabbitmq_users }}"
  run_once: true
