---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted

- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
